#
# Copyright (c) 2025, uiop <uiop@wasdhjkl.xyz>
#
# SPDX-License-Identifier: BSD-2-Clause
#

KERN_CODE_BASE := 0x10000
KERN_CODE_TOP  := 0x3FFFF
KERN_DATA_BASE := 0x50000
KERN_DATA_TOP  := 0x2FFFF
USER_CODE_BASE := 0x01000
USER_CODE_TOP  := 0x03FFF
USER_DATA_BASE := 0x05000
USER_DATA_TOP  := 0x02BFF

KERN_CODE_SECTORS := $(shell echo $$((($(KERN_CODE_TOP) - $(KERN_CODE_BASE)) / 512)))
KERN_DATA_SECTORS := $(shell echo $$((($(KERN_DATA_TOP) - $(KERN_CODE_BASE)) / 512)))
USER_CODE_SECTORS := $(shell echo $$((($(USER_CODE_TOP) - $(KERN_CODE_BASE)) / 512)))
USER_DATA_SECTORS := $(shell echo $$((($(USER_DATA_TOP) - $(KERN_CODE_BASE)) / 512)))

KERN_CODE_SEG := $(shell echo $$(($(KERN_CODE_BASE) >> 4)))
KERN_CODE_OFF := $(shell echo $$(($(KERN_CODE_BASE) & 0xF)))
KERN_DATA_SEG := $(shell echo $$(($(KERN_DATA_BASE) >> 4)))
KERN_DATA_OFF := $(shell echo $$(($(KERN_DATA_BASE) & 0xF)))
USER_CODE_SEG := $(shell echo $$(($(USER_CODE_BASE) >> 4)))
USER_CODE_OFF := $(shell echo $$(($(USER_CODE_BASE) & 0xF)))
USER_DATA_SEG := $(shell echo $$(($(USER_DATA_BASE) >> 4)))
USER_DATA_OFF := $(shell echo $$(($(USER_DATA_BASE) & 0xF)))

KERN_CODE_LBA := 1
KERN_DATA_LBA := $(shell echo $$(($(KERN_CODE_LBA) + $(KERN_CODE_SECTORS))))
USER_CODE_LBA := $(shell echo $$(($(KERN_DATA_LBA) + $(KERN_DATA_SECTORS))))
USER_DATA_LBA := $(shell echo $$(($(USER_CODE_LBA) + $(USER_CODE_SECTORS))))

NASM_DEFINES := \
	-DKERN_CODE_BASE=$(KERN_CODE_BASE) \
	-DKERN_CODE_TOP=$(KERN_CODE_TOP) \
	-DKERN_DATA_BASE=$(KERN_DATA_BASE) \
	-DKERN_DATA_TOP=$(KERN_DATA_TOP) \
	-DUSER_CODE_BASE=$(USER_CODE_BASE) \
	-DUSER_CODE_TOP=$(USER_CODE_TOP) \
	-DUSER_DATA_BASE=$(USER_DATA_BASE) \
	-DUSER_DATA_TOP=$(USER_DATA_TOP) \
	-DKERN_CODE_SECTORS=$(KERN_CODE_SECTORS) \
	-DKERN_DATA_SECTORS=$(KERN_DATA_SECTORS) \
	-DUSER_CODE_SECTORS=$(USER_CODE_SECTORS) \
	-DUSER_DATA_SECTORS=$(USER_DATA_SECTORS) \
	-DKERN_CODE_SEG=$(KERN_CODE_SEG) \
	-DKERN_CODE_OFF=$(KERN_CODE_OFF) \
	-DKERN_DATA_SEG=$(KERN_DATA_SEG) \
	-DKERN_DATA_OFF=$(KERN_DATA_OFF) \
	-DUSER_CODE_SEG=$(USER_CODE_SEG) \
	-DUSER_CODE_OFF=$(USER_CODE_OFF) \
	-DUSER_DATA_SEG=$(USER_DATA_SEG) \
	-DUSER_DATA_OFF=$(USER_DATA_OFF) \
	-DKERN_CODE_LBA=$(KERN_CODE_LBA) \
	-DKERN_DATA_LBA=$(KERN_DATA_LBA) \
	-DUSER_CODE_LBA=$(USER_CODE_LBA) \
	-DUSER_DATA_LBA=$(USER_DATA_LBA) \
